apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: client
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: client
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: client
        image: icanplayguitar94/iam:client-e5f05a006d53263c1af19202723736408618d7fc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3

        env:
        - name: HOME
          value: "/usr/home/iam"
        - name: TYPE 
          value: "client"
        - name: SERVER_PORT
          value: "5000"

        - name: ROUTER_HOST
          value: "router.default"
        - name: ROUTER_PORT
          value: "80"
        
        - name: USER_HOST
          value: "user.default"
        - name: USER_PORT
          value: "80"
        
        - name: AUTH_HOST
          value: "auth.default"
        - name: AUTH_PORT
          value: "80"

        - name: BUILDER_HOST
          value: "builder.default"
        - name: BUILDER_PORT
          value: "80"

---
apiVersion: v1
kind: Service
metadata:
  name: client
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "round_robin"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "5bcb4fd7-1834-4360-855c-c7dc98f53a34"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5000
