apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: StatefulSet
metadata:
  name: filesystem
spec:
  selector:
    matchLabels:
      app: filesystem
  replicas: 1 # tells deployment to run 2 pods matching the template
  serviceName: "filesystem"
  template:
    metadata:
      labels:
        app: filesystem
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: filesystem
        image: icanplayguitar94/iam:base-f71673374d245e911c8dd80a42e888ad92cfb105
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3

        env:
        - name: HOME
          value: "/usr/home/iam"
        - name: TYPE 
          value: "executor"
        - name: SERVER_PORT
          value: "5000"

        # FS CONFIG
        - name: FS_HOST
          value: "filesystem.default"
        - name: FS_PORT
          value: "80"

        ## DB CONFIG
        - name: DB_HOST
          value: "mysqldatabase.default"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dbconfig
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbconfig
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: dbconfig
              key: db_name

        volumeMounts:
        - name: root
          mountPath: /usr/home/iam
  volumeClaimTemplates:
  - metadata:
      name: root
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "do-block-storage"
      resources:
        requests:
          storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: filesystem
spec:
  selector:
    app: filesystem
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
