apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: job
spec:
  selector:
    matchLabels:
      app: job
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: job
    spec:
      serviceAccountName: job-service-account
      imagePullSecrets:
      - name: regcred
      containers:
      - name: job
        image: icanplayguitar94/iam:base-df01307df967fb6c6e05d1992cc9b7139f5db4f8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        
        env:
        - name: HOME
          value: "/usr/home/iam"
        - name: TYPE 
          value: "job"
        - name: SERVER_PORT
          value: "5000"
        - name: "ENVIRONMENT"
          value: "base"

        # FS CONFIG
        - name: FS_HOST
          value: "filesystem"
        - name: FS_PORT
          value: "80"

        ## DB CONFIG
        - name: DB_HOST
          value: "mysqldatabase.default"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: dbconfig
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbconfig
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: dbconfig
              key: db_name
---
apiVersion: v1
kind: Service
metadata:
  name: job
spec:
  selector:
    app: job
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
