FROM icanplayguitar94/iam:base-30e255655aade10de065bf861a420a3aa28f105c
ADD programs /usr/home/iam/programs
ADD images /usr/home/iam/images
ADD kubernetes /usr/home/iam/kubernetes
ADD templates/kubernetes /usr/home/iam/templates/kubernetes
