FROM icanplayguitar94/iam:base-minikube
ADD programs /usr/home/iam/programs
ADD images /usr/home/iam/images
ADD kubernetes /usr/home/iam/kubernetes
ADD templates/kubernetes /usr/home/iam/templates/kubernetes
