#!/bin/bash

TAG=$1
IMAGE=$2

curl -s http://iam-filesystem.default/images/$IMAGE | docker build --no-cache -t $TAG -
echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin 
docker push $TAG

kubectl apply -f http://iam-filesystem.default/kubernetes/$IMAGE