#!/bin/bash

scp -r $1/deploy.service $4@$2:$3
scp -r $1/deploy.tgz $4@$2:$3
scp -r $1/db-config.json $4@$2:$3
scp -r $1/fs-config.json $4@$2:$3
scp -r $1/install $4@$2:$3
scp -r $1/update $4@$2:$3
scp -r $1/clone $4@$2:$3
ssh $4@$2 "mkdir -p $3/public/dist"
scp -r $1/public/dist $4@$2:$3/public
ssh $4@$2 "bash $3/install"