apiVersion: v1 # for versions before 1.9.0 use apps/v1beta2
kind: Pod
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  imagePullSecrets:
  - name: regcred
  nodeSelector:
    type: basic
  containers:
  - name: {name}
    image: {imageRepo}:{name}
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 3306
        
    resources:
      requests:
        memory: "{memory}"
        cpu: "{cpu}"
      limits:
        memory: "{memory}"
        cpu: "{cpu}"

    env:
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {name}dbmasterpw
          key: secret
    ## DB CONFIG
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: {name}dbuser
          key: secret
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: {name}dbpassword
          key: secret
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: {name}dbname
          key: secret
        
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: ebs-volume
      
  volumes:
  - name: ebs-volume
    awsElasticBlockStore:
      volumeID: {ebsVolumeId}
      fsType: ext4

---
apiVersion: v1
kind: Service
metadata:
  name: {name}
spec:
  selector:
    app: {name}
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
