apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: {name}
spec:
  selector:
    matchLabels:
      app: {name}
  replicas: {replicas} # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: {name}
    spec:
      imagePullSecrets:
      - name: regcred
      nodeSelector:
        type: basic
      containers:
      - name: {name}
        image: {imageRepo}:{name}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /status
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 3
        
        resources:
          requests:
            memory: "{memory}"
            cpu: "{cpu}"
          limits:
            memory: "{memory}"
            cpu: "{cpu}"

        env:
        - name: HOME
          value: "/usr/home/iam"
        - name: TYPE 
          value: "executor"
        - name: SERVER_PORT
          value: "5000"
        - name: "ENVIRONMENT"
          value: "{name}"

        # FS CONFIG
        - name: FS_HOST
          value: "iam-filesystem"
        - name: FS_PORT
          value: "80"

        ## DB CONFIG
        - name: DB_HOST
          value: {database}
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: {database}dbuser
              key: secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {database}dbpassword
              key: secret
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: {database}dbame
              key: secret
---
apiVersion: v1
kind: Service
metadata:
  name: {name}
spec:
  selector:
    app: {name}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000