apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {name}
spec:
  schedule: {schedule}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {name}
            image: buildpack-deps:curl
            args:
            - /bin/sh
            - -ec
            - | 
              curl -H 'Content-type: application/json' -d '{data}' -X POST http://iam-router.default/executable/{exeUser}/{exeType}/{exeName}/run
          restartPolicy: Never
