name: templates
description: runs all the template generation

inputs:
  appDir:
    dir:
      default: .

  version:
    string:
      description: version to use for iam

  provider:
    string:
      description: provider building for (minikube | ec2 | ocean)
      
run:
  container:
    image:
      ref: ubuntu:18.04
    dirs:
      /src: $(appDir)
    envVars:
      TAG: "icanplayguitar94/iam:base-$(version)"
      PROVIDER: $(provider)
    workDir: /src
    cmd: 
    - bash
    - -c
    - | 
      mkdir -p kubernetes/apps/$PROVIDER

      # Base Image apps
      bash kubernetes/templates/filesystem.sh $TAG $PROVIDER
      bash kubernetes/templates/auth.sh $TAG $PROVIDER
      bash kubernetes/templates/router.sh $TAG $PROVIDER
      bash kubernetes/templates/user.sh $TAG $PROVIDER
      bash kubernetes/templates/admin.sh $TAG $PROVIDER
      
      # Image apps 
      bash kubernetes/templates/builder.sh icanplayguitar94/iam:builder-$(version) $PROVIDER
      bash kubernetes/templates/client.sh icanplayguitar94/iam:client-$(version) $PROVIDER
      bash kubernetes/templates/job.sh icanplayguitar94/iam:job-$(version) $PROVIDER
      bash kubernetes/templates/secret.sh icanplayguitar94/iam:secret-$(version) $PROVIDER