#!/bin/bash

scp -r $1/deploy.service $3@$2:$1
scp -r $1/deploy.tgz $3@$2:$1
scp -r $1/db-config.json $3@$2:$1
scp -r $1/fs-config.json $3@$2:$1
scp -r $1/install $3@$2:$1
scp -r $1/update $3@$2:$1
scp -r $1/clone $3@$2:$1
ssh $2 "mkdir -p $1/public/dist"
scp -r $1/public/dist $3@$2:$1/public
ssh $2 "bash $1/install $3"