apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-service-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: job-cluster-role
rules:
  -
    apiGroups: ["", "batch"]
    resources: ["cronjobs"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: job-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-cluster-role
subjects:
- kind: ServiceAccount
  name: job-service-account
  namespace: default