apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-service-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: secret-cluster-role
rules:
  -
    apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: secret-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-cluster-role
subjects:
- kind: ServiceAccount
  name: secret-service-account
  namespace: default