name: Release Request PR Base

on: 
  push:
    paths:
    - 'src/**'
    - 'images/base/**'
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '11.14.0'
    
    - name: Create Pull Request
      uses: vsoch/pull-request-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_PREFIX: "master"
        PULL_REQUEST_BRANCH: "release/base"
        PULL_REQUEST_TITLE: "Release Request for base"