name: Build Base Pull Request

on: 
  pull_request:
    paths:
    - 'apps/base/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '11.14.0'

    - name: Build Base
      run: bash apps/base/build.sh