name: Build Dependencies Docker

on: 
  push:
    branches:
      - 'release/dependencies'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Dependencies
      run: bash build-dependencies.sh $GITHUB_SHA
    - name: Push Docker 
      run: docker push icanplayguitar94/iam:dependencies-$GITHUB_SHA 
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        branch: deploy/dependencies
        commit-message: "Deploy Request for dependencies-${{ github.sha }}"
        base: master
        title: Deploy Request for dependencies-${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
