name: Build Base Docker

on: 
  push:
    branches:
      - 'release/base'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '11.14.0'
    - run: npm install && npm run build && npm pack && mv deploy-1.0.0.tgz images/base/deploy.tgz
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker
      run: docker build -t icanplayguitar94/iam:base-$GITHUB_SHA images/base 
    - name: Push Docker 
      run: docker push icanplayguitar94/iam:base-$GITHUB_SHA 
