name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '11.14.0'

    - name: Build Base
      if: "!contains(github.head_ref, 'deploy') && (contains(github.head_ref, 'base') || github.base_ref == 'release/base')"
      run: bash src/build.sh

    - name: Build Dashboard
      if: "!contains(github.head_ref, 'deploy') && (contains(github.head_ref, 'dashboard') || github.base_ref == 'release/dashboard')"
      run: bash public/build.sh -prod