name: Build Base Pull Request

on: 
  pull_request:
    paths:
    - 'apps/base/**'

jobs:
  build:
    container: opctl:0.1.45-dind
    steps:
    - uses: actions/checkout@v1

    - name: Build Base
      run: opctl run test