name: Build Filesystem Docker

on: 
  push:
    branches:
      - 'release/filesystem'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Filesystem
      run: bash build-filesystem.sh $GITHUB_SHA
    - name: Push Docker 
      run: docker push icanplayguitar94/iam:filesystem-$GITHUB_SHA 
