name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker
      run: export TAG=$(date +%s) && docker build -t icanplayguitar94/iam:dependencies-$TAG images/dependencies && docker push icanplayguitar94/iam:dependencies-$TAG 
