name: Build Filesystem Docker

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Build Docker
      run: docker build -t icanplayguitar94/iam:filesystem-$GITHUB_SHA images/filesystem 
    - name: Push Docker 
      run: docker push icanplayguitar94/iam:filesystem-$GITHUB_SHA 
