name: Release Request PR Filesystem

on: 
  push:
    paths:
    - 'images/filesystem/**'
    branches:
    - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1    
    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "master"
        destination_branch: "release/filesystem"          # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: ":crown: *An automated PR*"  # Full markdown support, requires pr_title to be set
        github_token: ${{ secrets.GITHUB_TOKEN }}