name: Build Base PR

on: 
  push:
    branches:
    - base*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '11.14.0'
    - name: Build Base
      run: bash src/build.sh
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"          # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: ":crown: *An automated PR*"  # Full markdown support, requires pr_title to be set
        github_token: ${{ secrets.GITHUB_TOKEN }}