name: Release Base

on: 
  push:
    branches:
    - 'release/base'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - uses: actions/setup-node@v1
      with:
        node-version: '11.14.0'
    
    - name: Build Base
      run: bash build.sh base $GITHUB_SHA push

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"          # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: ":crown: *An automated PR*"  # Full markdown support, requires pr_title to be set
        github_token: ${{ secrets.ACTIONS_TOKEN }}
