name: Release Base

on: 
  push:
    branches:
    - 'release/base'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - uses: actions/setup-node@v1
      with:
        node-version: '11.14.0'
    
    - name: Build Base
      run: bash build.sh base $GITHUB_SHA push
    
    - name: Commit Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b deploy/base-${{ github.sha }}
        git commit -m "Deploy Request for base ${{ github.sha }}" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: deploy/base-${{ github.sha }}
        github_token: ${{ secrets.ACTIONS_TOKEN }}
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACTIONS_TOKEN }}
