name: Release Filesystem

on: 
  push:
    branches:
      - 'release/filesystem'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    
    - name: Build Filesystem
      run: bash build.sh filesystem $GITHUB_SHA push
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1
      with:
        branch: deploy/filesystem
        commit-message: "Deploy Request for filesystem-${{ github.sha }}"
        base: master
        title: Deploy Request for filesystem-${{ github.sha }}
        token: ${{ secrets.GITHUB_TOKEN }}
