name: Release Base

on: 
  push:
    branches:
    - 'release/base'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
    - uses: actions/setup-node@v1
      with:
        node-version: '11.14.0'
    
    - name: Build Base
      run: bash build.sh base $GITHUB_SHA push

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b deploy/base-${{ github.sha }}
        git commit -m "Deploy updates for base" -a
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: deploy/base-${{ github.sha }}
        github_token: ${{ secrets.ACTIONS_TOKEN }}

    - name: Create Pull Request
      uses: repo-sync/pull-request@v2
      with:
        source_branch: "deploy/base-${{ github.sha }}"
        destination_branch: "master"          # If blank, default: master
        pr_title: "Pulling ${{ github.ref }} into master"
        pr_body: ":crown: *An automated PR*"  # Full markdown support, requires pr_title to be set
        github_token: ${{ secrets.ACTIONS_TOKEN }}
